spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/api/accounts/**
#            - Path=/api/profiles/**
#
#        - id: transaction-service
#          uri: lb://TRANSACTION-SERVICE
#          predicates:
#            - Path=/api/transactions/**
#            - Path=/api/tranAccounts/**
#
#        - id: ai-recommendation-service
#          uri: lb://AI-RECOMMENDATION-SERVICE
#          predicates:
#            - Path=/api/recommendations/**
#
#server:
#  port: 8080
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
