#spring.application.name=user-service


spring:
    application:
      name: user-service
    config:
      import: optional:configserver:http://localhost:8888
#    datasource:
#      url: jdbc:mysql://localhost:3306/fins_user_db
#      username: root
#      password: password
#    jpa:
#      hibernate:
#        ddl-auto: update
#      database-platform: org.hibernate.dialect.MySQL8Dialect
#
#server:
#  port: 8081
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/