spring:
#  application:
#    name: ai-recommendation-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/fins_recommendations
      database: fins_recommendations
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  ai:
    model:
      chat: ollama
    ollama:
      base-url: http://localhost:11434
      init:
        pull-model-strategy: never
        timeout: 30m
        max-retries: 0
      chat:
        options:
#          model: gemma3:1b
          model: llama3.2
          keep-alive: 30m
          timeout: 30m
          format: json

jwt:
  secret: a2ZybWxld3JmZ29hc2dybWZ1d2VyZ3JtY3RzZmdyYWZhY3RzZg==
  expiration: 604800000

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

rabbitmq:
  exchange:
    name: finance.exchange
  queue:
    name: transaction.queue
  routing:
    key: transaction.creation