server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/accounts/**,/api/profiles/**,/api/auth/**
        - id: transaction-service
          uri: lb://TRANSACTION-SERVICE
          predicates:
            - Path=/api/transactions/**,/api/tranAccounts/**
        - id: ai-recommendation-service
          uri: lb://AI-RECOMMENDATION-SERVICE
          predicates:
            - Path=/api/recommendations/**

jwt:
  secret: a2ZybWxld3JmZ29hc2dybWZ1d2VyZ3JtY3RzZmdyYWZhY3RzZg==

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
